services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image:  ybaher/raisin-classification:0307886
    ports:
      - "8888:8888"
    volumes:
      - .:/workplace
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64