name: craisins
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas=2.3.1
  - altair=5.5.0
  - numpy=2.0.2
  - ipykernel=6.30.1
  - scikit-learn=1.6.1
  - matplotlib=3.9.1
  - conda-lock=3.0.4
  - mamba
  - conda
  - pandera
  - click
  - quarto
  - pip:
      - ucimlrepo==0.0.7
