name: base
channels:
  - conda-forge
dependencies:
  - python=3.12
  - conda=25.7.0
  - mamba=2.1.1
  - pip
  - miniforge_console_shortcut=1
  - numpy
  - altair
  - pandas
prefix: C:\Users\eric_\miniforge3
